# Generated by Django 4.2.3 on 2023-08-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_turistico', '0003_alter_pontoturistico_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='aprovado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
